name = "dentalautomations-io"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "dentalautomations-io"

# Cloudflare Pages configuration
pages_build_output_dir = "dist/public"

# Environment variables (will be set via Cloudflare dashboard)
# [vars]
# NODE_ENV = "production"

# Database configuration will be added via Cloudflare dashboard secrets